export const SCHEDULE_PENDING_STATUS = {
    CREATING:"CREATING",
    UPDATING:"UPDATING",
    DELETING:"DELETING"
}
export const SCHEDULE_COMPLETED_STATUS = {
    CREATING:"CREATED",
    UPDATING:"UPDATED",
    DELETING:"DELETED"
}